INSERT INTO PRODUCTLIST VALUES(1,330,'Watch');
INSERT INTO PRODUCTLIST VALUES(2,40,'LED Remote');
INSERT INTO PRODUCTLIST VALUES(3,800,'Laptop');
INSERT INTO EXRATE VALUES('EUR',0.9);
INSERT INTO EXRATE VALUES('INR',70);
