CREATE TABLE PRODUCTLIST
(
    ITEMID  integer PRIMARY KEY,
    ITEM_COST    integer NOT NULL,
    ITEM_NAME   varchar(30) NOT NULL
);

CREATE TABLE EXRATE
(
    CURRENCY_ALPHA  varchar(30) PRIMARY KEY,
    CURRENCY_VALUE   varchar(30) NOT NULL
);